name = "nastech-agent"
main = "src/index.js"
compatibility_date = "2026-10-05"
workers_dev = true

[[kv_namespaces]]
binding = "NASTECH_ASSETS"
id = "ff12d5a5324d44b599d8319edabc4adb"

[observability]
enabled = true